apiVersion: v1
kind: ConfigMap
metadata:
  name: oidc-authservice-parameters
data:
  AUTHSERVICE_URL_PREFIX: /authservice/
  CLIENT_ID: MLP-Kubeflow-dev
  CLIENT_SECRET: Ts6qgz1HCsZIf3gDAknLiPZR8zg2rt8lVpmRUftWCT2qfzm3CkN0CzsxGP8Z6Y6Z
  OIDC_AUTH_URL: /dex/auth
  OIDC_PROVIDER: 'http://dex.auth.svc.cluster.local:5556/dex'
  OIDC_SCOPES: profile email groups
  PORT: '"8080"'
  REDIRECT_URL: /login/oidc
  SKIP_AUTH_URI: /dex
  STORE_PATH: /var/lib/authservice/data.db
  USERID_CLAIM: email
  USERID_HEADER: kubeflow-userid
  USERID_PREFIX: ''

