apiVersion: v1
kind: Secret
metadata:
  name: memberlist
  namespace: metallb-system
stringData:
  secretkey: "4p3ArHhvi6oOoRPQ2RbUZWYLPA96hHZUIohfR8q6UUnqn8Te0NYAgzn5xhIF4nkM\nTreRl6BFmzaylTK+oqYopdfM5+RMF0WmCfBj6ee7Qzn+VVu0R9ANvWL5+w664qat\neRh2tmNIMyFRISz+LDWDiNDFl3IwJdDfRD3tGVhx8T4="
